import type { Metadata } from "next";
import "./globals.css";
import { MantineProvider } from '@mantine/core';
import { HeaderMegaMenu as Header } from "./components/Header";
import {FooterCentered as Footer} from "./components/Footer";
import '@mantine/core/styles.css';
import { ColorSchemeScript } from '@mantine/core';

export const metadata: Metadata = {
  title: "TOPEXPERT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider>
          <Header/>
          <main className="px-[100px]">{children}</main>
          <Footer/>
        </MantineProvider>
      </body>
    </html>
  );
}
